<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Bios;
use App\Models\Emulator;
use App\Models\Franchise;
use App\Models\Console;

class BiosEmulatorFranchiseSeeder extends Seeder
{
    public function run(): void
    {
        // 1. SEED BIOS
        $biosData = [
            [
                'system' => 'PlayStation 2 (PS2)',
                'console_slug' => 'playstation-2',
                'files' => 'SCPH-39001, SCPH-70012, SCPH-90006',
                'version' => 'USA / Europe / Japan v2.30',
                'size' => '14.2 MB',
                'format' => '.BIN / .ROM',
                'md5' => 'd5ce512e94628f80424564c7810df66c',
                'sha1' => '9a5e523efb672a9dfa7a8d54c1f59239d5621415',
                'emulator' => 'PCSX2, NetherSX2, AetherSX2',
                'download_url' => 'https://archive.org/download/SonyPlayStation2BIOS/Sony_PlayStation_2_BIOS_Pack.zip',
                'description' => 'Pack oficial de BIOS de PlayStation 2 para emular con 100% de compatibilidad en PC y Android.',
                'order' => 1,
            ],
            [
                'system' => 'PlayStation 1 (PS1 / PSX)',
                'console_slug' => 'playstation-1',
                'files' => 'SCPH-1001, SCPH-5500, SCPH-5501, SCPH-7001',
                'version' => 'NTSC-U / PAL / NTSC-J',
                'size' => '2.0 MB',
                'format' => '.BIN',
                'md5' => 'dc2b9bf8da62ec93e86851b0f01c04b0',
                'sha1' => '1e68c238122c44249a5b6c37494f6c49830882e3',
                'emulator' => 'DuckStation, ePSXe, RetroArch (Beetle PSX / SwanStation)',
                'download_url' => 'https://archive.org/download/ps1-bios-pack-scph/PS1_BIOS_Collection.zip',
                'description' => 'BIOS oficiales de Sony PlayStation 1 con sonido original de inicio (Sony Computer Entertainment).',
                'order' => 2,
            ],
            [
                'system' => 'PlayStation 3 (PS3 Firmware)',
                'console_slug' => 'playstation-3',
                'files' => 'PS3UPDAT.PUP',
                'version' => 'Official Firmware v4.91',
                'size' => '200.4 MB',
                'format' => '.PUP',
                'md5' => '3f3fa55f2420f182c1615d852a382be7',
                'sha1' => '28f1338a9d94943717df30faefc0e5a95904fa15',
                'emulator' => 'RPCS3',
                'download_url' => 'http://dus01.ps3.update.playstation.net/update/ps3/image/us/2024_0227_36814b7e8d5e5db5c6131f496739178f/PS3UPDAT.PUP',
                'description' => 'Software de sistema original de PlayStation 3 descargable directamente de servidores oficiales de Sony para RPCS3.',
                'order' => 3,
            ],
            [
                'system' => 'Sega Dreamcast',
                'console_slug' => 'sega-dreamcast',
                'files' => 'dc_boot.bin, dc_flash.bin',
                'version' => 'v1.01d Region Free',
                'size' => '2.1 MB',
                'format' => '.BIN',
                'md5' => 'e10c53c2f8b90bab96ead2d368858623',
                'sha1' => 'a953e5e6fb4e9b9cf9c6b8c0d1e1f1a4e7c3b2a1',
                'emulator' => 'Flycast, Redream, RetroArch',
                'download_url' => 'https://archive.org/download/sega-dreamcast-bios/dreamcast_bios.zip',
                'description' => 'BIOS y memoria flash de Sega Dreamcast para arranque con animación en espiral y soporte VMU.',
                'order' => 4,
            ],
            [
                'system' => 'Nintendo DS / DSi',
                'console_slug' => 'nintendo-ds',
                'files' => 'bios7.bin, bios9.bin, firmware.bin',
                'version' => 'Official Clean Dump',
                'size' => '260 KB',
                'format' => '.BIN',
                'md5' => 'df692a80a5b1bc90728bc3dfc76cd948',
                'sha1' => '5ef8bb90f77987829288e1a7ab402127161e1140',
                'emulator' => 'MelonDS, DeSmuME, DraStic',
                'download_url' => 'https://archive.org/download/nds-bios-pack/nds_bios_firmware.zip',
                'description' => 'Archivos ARM7 y ARM9 de Nintendo DS para renderizado nativo de menús y Wi-Fi en emuladores.',
                'order' => 5,
            ],
            [
                'system' => 'Game Boy Advance (GBA)',
                'console_slug' => 'game-boy-advance',
                'files' => 'gba_bios.bin',
                'version' => 'Official Nintendo GBA',
                'size' => '16 KB',
                'format' => '.BIN',
                'md5' => 'a860e8c0b6d573d191e4ec7db1b1e4f6',
                'sha1' => '300c20df6731a33952ded8c436f7f18b12e6207e',
                'emulator' => 'mGBA, VisualBoyAdvance, RetroArch',
                'download_url' => 'https://archive.org/download/gba-bios-official/gba_bios.bin',
                'description' => 'BIOS de Game Boy Advance para el logo de inicio Nintendo y máxima precisión de timings.',
                'order' => 6,
            ],
        ];

        foreach ($biosData as $item) {
            $console = Console::where('slug', $item['console_slug'])->first();
            $item['console_id'] = $console?->id;
            Bios::updateOrCreate(['system' => $item['system']], $item);
        }

        // 2. SEED EMULATORS
        $emulatorsData = [
            [
                'name' => 'PCSX2',
                'system' => 'PlayStation 2',
                'icon' => 'disc',
                'platforms' => ['Windows', 'Linux', 'macOS'],
                'version' => 'v2.0 Stable',
                'features' => ['Resolución 4K/8K', 'Vulkan & DirectX 12', 'Soporte DualSense & Xbox', 'RetroAchievements'],
                'license' => 'GPLv3 Open Source',
                'website' => 'https://pcsx2.net',
                'download_url' => 'https://pcsx2.net/downloads',
                'description' => 'El emulador definitivo de PlayStation 2. Permite jugar miles de títulos a 60 FPS con texturas en alta definición y filtros widescreen.',
                'order' => 1,
            ],
            [
                'name' => 'DuckStation',
                'system' => 'PlayStation 1 (PS1)',
                'icon' => 'disc-2',
                'platforms' => ['Windows', 'Android', 'Linux', 'macOS'],
                'version' => 'Latest Rolling',
                'features' => ['PGXP (Sin temblores 3D)', 'Corrección de perspectiva', 'Overclock de CPU', 'Upscaling 4K'],
                'license' => 'GPLv3 Open Source',
                'website' => 'https://github.com/stenzek/duckstation',
                'download_url' => 'https://github.com/stenzek/duckstation/releases',
                'description' => 'El mejor emulador de PlayStation 1 enfocado en precisión, velocidad y capacidades de remasterización PGXP.',
                'order' => 2,
            ],
            [
                'name' => 'Dolphin Emulator',
                'system' => 'Nintendo GameCube & Wii',
                'icon' => 'box',
                'platforms' => ['Windows', 'Android', 'macOS', 'Linux'],
                'version' => 'v5.0 / Development',
                'features' => ['Emulación Wiimote Bluetooth', 'Texturas HD personalizadas', 'Netplay multijugador', '60 FPS Hacks'],
                'license' => 'GPLv2+ Open Source',
                'website' => 'https://dolphin-emu.org',
                'download_url' => 'https://dolphin-emu.org/download/',
                'description' => 'Emulador legendario para GameCube y Wii. Rendimiento impecable en computadoras y teléfonos inteligentes modernos.',
                'order' => 3,
            ],
            [
                'name' => 'PPSSPP',
                'system' => 'PlayStation Portable (PSP)',
                'icon' => 'smartphone',
                'platforms' => ['Windows', 'Android', 'iOS', 'macOS', 'Linux'],
                'version' => 'v1.17.1',
                'features' => ['Upscaling HD/4K', 'Soporte Mandos Bluetooth', 'Guardado Rápido', 'Filtros de Post-procesado'],
                'license' => 'GPLv2+ Open Source',
                'website' => 'https://www.ppsspp.org',
                'download_url' => 'https://www.ppsspp.org/download/',
                'description' => 'Emulador rápido y portátil de PSP. Funciona a máxima velocidad en casi cualquier dispositivo Android o PC.',
                'order' => 4,
            ],
            [
                'name' => 'RPCS3',
                'system' => 'PlayStation 3 (PS3)',
                'icon' => 'cpu',
                'platforms' => ['Windows', 'Linux', 'macOS'],
                'version' => 'v0.0.33 Alpha',
                'features' => ['Resolución 4K/8K', 'Desbloqueo a 60/120 FPS', 'Vulkan Renderer', 'Soporte PSN Local'],
                'license' => 'GPLv2 Open Source',
                'website' => 'https://rpcs3.net',
                'download_url' => 'https://rpcs3.net/download',
                'description' => 'Emulador y depurador open source de PlayStation 3 con más del 70% del catálogo jugable a máxima fluidez.',
                'order' => 5,
            ],
            [
                'name' => 'mGBA',
                'system' => 'Game Boy Advance / Color',
                'icon' => 'gamepad',
                'platforms' => ['Windows', 'macOS', 'Linux', '3DS', 'Switch'],
                'version' => 'v0.10.3',
                'features' => ['Soporte Cable Link Local/Red', 'Sensor Solar y Giroscopio', 'Rebobinado en tiempo real', 'Game Boy Printer'],
                'license' => 'MPL 2.0 Open Source',
                'website' => 'https://mgba.io',
                'download_url' => 'https://mgba.io/downloads.html',
                'description' => 'El emulador de Game Boy Advance más preciso y ligero disponible, ideal para ROM hacks y juegos originales.',
                'order' => 6,
            ],
            [
                'name' => 'MelonDS',
                'system' => 'Nintendo DS / DSi',
                'icon' => 'laptop',
                'platforms' => ['Windows', 'Linux', 'macOS', 'Android'],
                'version' => 'v0.9.5',
                'features' => ['Renderizado OpenGL 3D', 'Wi-Fi Online Nintendo WFC', 'Micrófono y Pantalla Táctil', 'Modo DSi'],
                'license' => 'GPLv3 Open Source',
                'website' => 'https://melonds.kuribo64.net',
                'download_url' => 'https://melonds.kuribo64.net/downloads.php',
                'description' => 'Emulador de Nintendo DS de nueva generación enfocado en emular el hardware con precisión milimétrica.',
                'order' => 7,
            ],
            [
                'name' => 'RetroArch',
                'system' => 'Multi-Sistema (Todo en Uno)',
                'icon' => 'layers',
                'platforms' => ['Windows', 'Android', 'iOS', 'macOS', 'Linux', 'Steam Deck', 'Xbox'],
                'version' => 'v1.19.1',
                'features' => ['Más de 80 Núcleos Libretro', 'Shaders CRT Retro', 'RetroAchievements', 'Netplay Cross-platform'],
                'license' => 'GPLv3 Open Source',
                'website' => 'https://www.retroarch.com',
                'download_url' => 'https://www.retroarch.com/?page=platforms',
                'description' => 'La suite universal de emulación frontend. Compatible con casi cualquier consola histórica mediante núcleos descargables.',
                'order' => 8,
            ],
        ];

        foreach ($emulatorsData as $item) {
            Emulator::updateOrCreate(['name' => $item['name']], $item);
        }

        // 3. SEED FRANCHISES
        $franchisesData = [
            [
                'name' => 'Pokémon',
                'slug' => 'pokemon',
                'subtitle' => 'Atrapalos a todos en todas las generaciones',
                'description' => 'Desde Kanto hasta Paldea. Todas las ediciones legendarias de Game Boy, GBA, Nintendo DS, 3DS y Switch.',
                'image' => 'https://images.unsplash.com/photo-1613770920295-90f81544dd7c?w=700&fit=crop',
                'icon' => 'sparkles',
                'color' => '#EAB308',
                'search_terms' => ['Pokemon', 'Pokémon', 'Pocket Monsters'],
                'order' => 1,
            ],
            [
                'name' => 'Super Mario',
                'slug' => 'super-mario',
                'subtitle' => 'El rey de las plataformas y aventuras',
                'description' => 'Clásicos eternos en 2D y 3D: Super Mario World, Super Mario 64, Sunshine, Galaxy, Odyssey y spin-offs.',
                'image' => 'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=700&fit=crop',
                'icon' => 'layers',
                'color' => '#EF4444',
                'search_terms' => ['Super Mario', 'Mario Kart', 'Mario Party', 'Mario & Luigi', 'Paper Mario', 'Mario Bros'],
                'order' => 2,
            ],
            [
                'name' => 'The Legend of Zelda',
                'slug' => 'the-legend-of-zelda',
                'subtitle' => 'El viaje legendario del Héroe del Tiempo',
                'description' => 'Explora Hyrule en Ocarina of Time, Majora\'s Mask, The Wind Waker, Twilight Princess y Breath of the Wild.',
                'image' => 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=700&fit=crop',
                'icon' => 'shield',
                'color' => '#10B981',
                'search_terms' => ['Zelda', 'Link', 'Ocarina of Time', 'Majora', 'Wind Waker', 'Twilight Princess'],
                'order' => 3,
            ],
            [
                'name' => 'Grand Theft Auto',
                'slug' => 'grand-theft-auto',
                'subtitle' => 'Mundo abierto, crimen y libertad total',
                'description' => 'Las entregas más revolucionarias de Rockstar: Vice City, San Andreas, GTA III, Liberty City Stories y GTA IV.',
                'image' => 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=700&fit=crop',
                'icon' => 'flame',
                'color' => '#F59E0B',
                'search_terms' => ['Grand Theft Auto', 'GTA', 'Vice City', 'San Andreas'],
                'order' => 4,
            ],
            [
                'name' => 'Resident Evil',
                'slug' => 'resident-evil',
                'subtitle' => 'La cumbre del Survival Horror',
                'description' => 'Raccoon City y más allá. Experimenta Resident Evil 1, 2, 3 Nemesis, Code: Veronica y el influyente Resident Evil 4.',
                'image' => 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=700&fit=crop',
                'icon' => 'skull',
                'color' => '#991B1B',
                'search_terms' => ['Resident Evil', 'Biohazard', 'Nemesis', 'Code Veronica'],
                'order' => 5,
            ],
            [
                'name' => 'God of War',
                'slug' => 'god-of-war',
                'subtitle' => 'La venganza mitológica de Kratos',
                'description' => 'La saga griega completa de Santa Monica Studio: God of War I, II, III, Chains of Olympus y Ghost of Sparta.',
                'image' => 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=700&fit=crop',
                'icon' => 'swords',
                'color' => '#B91C1C',
                'search_terms' => ['God of War', 'Kratos', 'Chains of Olympus', 'Ghost of Sparta'],
                'order' => 6,
            ],
            [
                'name' => 'Dragon Ball',
                'slug' => 'dragon-ball',
                'subtitle' => 'Combates Z a velocidad supersónica',
                'description' => 'Budokai Tenkaichi 3, Infinite World, Budokai 3, Legacy of Goku y todos los enfrentamientos Saiyajin.',
                'image' => 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=700&fit=crop',
                'icon' => 'zap',
                'color' => '#EA580C',
                'search_terms' => ['Dragon Ball', 'Budokai', 'Tenkaichi', 'Legacy of Goku', 'Kakarot'],
                'order' => 7,
            ],
            [
                'name' => 'Sonic the Hedgehog',
                'slug' => 'sonic-the-hedgehog',
                'subtitle' => 'Velocidad sónica en consolas Sega y Nintendo',
                'description' => 'De Mega Drive a Dreamcast y GameCube: Sonic 1, 2, 3 & Knuckles, Sonic Adventure 1 & 2 y Sonic Heroes.',
                'image' => 'https://images.unsplash.com/photo-1579373903781-fd5c0c30c4cd?w=700&fit=crop',
                'icon' => 'gauge',
                'color' => '#2563EB',
                'search_terms' => ['Sonic', 'Hedgehog', 'Sonic Adventure', 'Sonic Heroes'],
                'order' => 8,
            ],
            [
                'name' => 'Tekken',
                'slug' => 'tekken',
                'subtitle' => 'El Torneo del Rey del Puño de Hierro',
                'description' => 'La franquicia de lucha más prestigiosa de PlayStation: Tekken 3, Tekken 5, Tekken Tag Tournament y Dark Resurrection.',
                'image' => 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=700&fit=crop',
                'icon' => 'award',
                'color' => '#D97706',
                'search_terms' => ['Tekken', 'Iron Fist', 'Dark Resurrection'],
                'order' => 9,
            ],
            [
                'name' => 'Crash Bandicoot',
                'slug' => 'crash-bandicoot',
                'subtitle' => 'El marsupial más loco de Naughty Dog',
                'description' => 'La trilogía original de PS1, Crash Team Racing (CTR), Crash Bash y The Wrath of Cortex.',
                'image' => 'https://images.unsplash.com/photo-1551103782-8ab07afd45c1?w=700&fit=crop',
                'icon' => 'gamepad-2',
                'color' => '#C2410C',
                'search_terms' => ['Crash Bandicoot', 'Crash Team Racing', 'CTR', 'Crash Bash'],
                'order' => 10,
            ],
        ];

        foreach ($franchisesData as $item) {
            Franchise::updateOrCreate(['slug' => $item['slug']], $item);
        }
    }
}
