<?php

namespace Database\Seeders;

use App\Models\Bios;
use App\Models\Console;
use App\Models\Emulator;
use Illuminate\Database\Seeder;

class BiosEmulatorSeeder extends Seeder
{
    /**
     * Sincronización completa de 38 BIOS packs de CDRomance + 19 Emuladores Modernos
     */
    public function run(): void
    {
        // 1. BIOS DIRECTORY (38 Packs de CDRomance + PS3 Firmware Oficial)
        $biosData = [
            [
                'system' => 'PlayStation 2 (PS2) - All Regions Pack',
                'console_slug' => 'playstation-2',
                'files' => 'SCPH-39001, SCPH-70012, SCPH-90006, SCPH-10000, SCPH-77001',
                'version' => 'USA / Europe / Japan v2.30 Complete',
                'size' => '43.8 MB',
                'format' => '.BIN / .ROM',
                'md5' => 'd60adff025ff16f462abec6613f4c109',
                'sha1' => '361e9f0f4c612f6679c7edf5a85fc0172b6b0aaf',
                'emulator' => 'PCSX2, NetherSX2, AetherSX2',
                'download_url' => 'https://pub-1b8008184ad14b7b9c5a25fe74b145b6.r2.dev/vault/bios/playstation-2-ps2-all-regions-pack.7z',
                'description' => 'Colección definitiva de BIOS de PlayStation 2 para todas las regiones (NTSC-U, PAL, NTSC-J). Imprescindible para PCSX2 en PC y NetherSX2 en Android.',
                'order' => 1,
            ],
            [
                'system' => 'PlayStation 1 (PSX / PSOne) Bios Pack',
                'console_slug' => 'playstation',
                'files' => 'SCPH-1001 (US), SCPH-5500 (JP), SCPH-5502 (EU), SCPH-7001',
                'version' => 'Redump Verified All Regions',
                'size' => '1,005 KB',
                'format' => '.BIN',
                'md5' => '74dc266d22a631d5eee95f00ccccb1c4',
                'sha1' => 'db030b13bf9e7f6c1b14c0500def61169dfa59f4',
                'emulator' => 'DuckStation, SwanStation, ePSXe, RetroArch',
                'download_url' => 'https://pub-1b8008184ad14b7b9c5a25fe74b145b6.r2.dev/vault/bios/playstation-1-psx-psone-bios-pack.7z',
                'description' => 'Pack oficial de BIOS de PS1 verificado por Redump. Incluye la icónica secuencia de audio de arranque de Sony Computer Entertainment.',
                'order' => 2,
            ],
            [
                'system' => 'PlayStation 3 (PS3 Official Firmware)',
                'console_slug' => 'playstation-3',
                'files' => 'PS3UPDAT.PUP',
                'version' => 'Official Firmware v4.91',
                'size' => '270 KB',
                'format' => '.PUP',
                'md5' => 'd1a34e1d87acd6b3fd076faf35f50aa0',
                'sha1' => '5b8f26728d2629b2a340a78d4a80873f3878b8b7',
                'emulator' => 'RPCS3',
                'download_url' => 'https://pub-1b8008184ad14b7b9c5a25fe74b145b6.r2.dev/vault/bios/playstation-3-ps3-official-firmware.pup',
                'description' => 'Firmware oficial de sistema de PlayStation 3 servido directamente desde la infraestructura de Sony para arranque en RPCS3.',
                'order' => 3,
            ],
            [
                'system' => 'Sega Dreamcast Bios Pack',
                'console_slug' => 'dreamcast',
                'files' => 'dc_boot.bin, dc_flash.bin, VMS BIOS.bin, Utopia CD Loader',
                'version' => 'v1.01d Region Free Clean Dump',
                'size' => '2.9 MB',
                'format' => '.BIN / .CDI',
                'md5' => '0ae4551f321770e3661724fc69d57230',
                'sha1' => 'c000c36f00bfaa5a30758741b52b3ece96fcdebf',
                'emulator' => 'Flycast, Redream, RetroArch',
                'download_url' => 'https://pub-1b8008184ad14b7b9c5a25fe74b145b6.r2.dev/vault/bios/sega-dreamcast-bios-pack.7z',
                'description' => 'BIOS y memoria flash de Sega Dreamcast con arranque de espiral naranja/azul y soporte para memoria VMU.',
                'order' => 4,
            ],
            [
                'system' => 'Sega Saturn Bios (All Regions)',
                'console_slug' => 'sega-genesis',
                'files' => 'sega_101.bin, mpr-17933.bin, mpr-18811-mx.ic8',
                'version' => 'USA / Europe / Japan v1.00 - v1.01',
                'size' => '1.8 MB',
                'format' => '.BIN',
                'md5' => '3a09a45e15e0eee3306a3f2767477f45',
                'sha1' => '54953c0422e4f301edaa4d191e6ed860fc274581',
                'emulator' => 'Mednafen, Beetle Saturn, Kronos, YabaSanshiro',
                'download_url' => 'https://pub-1b8008184ad14b7b9c5a25fe74b145b6.r2.dev/vault/bios/sega-saturn-bios-all-regions.zip',
                'description' => 'Colección de BIOS oficiales de Sega Saturn para todas las regiones (Japón, América y Europa).',
                'order' => 5,
            ],
            [
                'system' => 'Sega Saturn Action Replay ROM',
                'console_slug' => 'sega-genesis',
                'files' => 'Action_Replay_Plus_v2.02.bin',
                'version' => 'Action Replay 4M Plus v2.02',
                'size' => '39 KB',
                'format' => '.BIN',
                'md5' => '37024b4d1c7d508422caec59038f2bae',
                'sha1' => '2f50a4ca778e22dc2ba49d8c2583c428096d7afb',
                'emulator' => 'Mednafen, Beetle Saturn, Kronos',
                'download_url' => 'https://pub-1b8008184ad14b7b9c5a25fe74b145b6.r2.dev/vault/bios/sega-saturn-action-replay-rom.zip',
                'description' => 'ROM del cartucho Action Replay para Sega Saturn. Permite saltarse bloqueos regionales y cargar trucos.',
                'order' => 6,
            ],
            [
                'system' => 'Sega Saturn CD Block ROM',
                'console_slug' => 'sega-genesis',
                'files' => 'Saturn CD Block ROM (Ymir).bin',
                'version' => 'Ymir Clean Dump',
                'size' => '162 KB',
                'format' => '.BIN',
                'md5' => '',
                'sha1' => '',
                'emulator' => 'Mednafen, Kronos',
                'download_url' => 'https://pub-1b8008184ad14b7b9c5a25fe74b145b6.r2.dev/vault/bios/sega-saturn-bios-all-regions.zip',
                'description' => 'ROM de arranque y bloque de lectura para Sega Saturn. Incluido dentro de la colección completa oficial de Sega Saturn.',
                'order' => 7,
            ],
            [
                'system' => 'Sega CD / Mega-CD BIOS',
                'console_slug' => 'sega-genesis',
                'files' => 'bios_CD_U.bin, bios_CD_E.bin, bios_CD_J.bin',
                'version' => 'Model 1 & 2 (USA, EUR, JAP)',
                'size' => '1.0 MB',
                'format' => '.BIN',
                'md5' => 'd2d53b863c3ae0ab6573f9c31053a2a5',
                'sha1' => 'e4eb49e5bba093b0ee453e2754653ae83e9980b5',
                'emulator' => 'Genesis Plus GX, PicoDrive, Kega Fusion',
                'download_url' => 'https://pub-1b8008184ad14b7b9c5a25fe74b145b6.r2.dev/vault/bios/sega-cd-mega-cd-bios.zip',
                'description' => 'BIOS oficiales para el add-on Sega CD y Mega-CD en todas las regiones con animaciones de arranque estéreo.',
                'order' => 8,
            ],
            [
                'system' => 'Sega 32X BIOS',
                'console_slug' => 'sega-genesis',
                'files' => '32X_G.bin, 32X_M.bin, 32X_S.bin',
                'version' => 'Master & Slave CPU BIOS',
                'size' => '2 KB',
                'format' => '.BIN',
                'md5' => '3a61bdf093baa504fa6af5ca8b28e16e',
                'sha1' => 'cca02feb995044b5cb427a82ac6c580c32aa6070',
                'emulator' => 'PicoDrive, Kega Fusion, RetroArch',
                'download_url' => 'https://pub-1b8008184ad14b7b9c5a25fe74b145b6.r2.dev/vault/bios/sega-32x-bios.zip',
                'description' => 'Archivos de arranque de procesador dual SH-2 para la expansión Sega 32X.',
                'order' => 9,
            ],
            [
                'system' => 'Sega Genesis / Megadrive (TMSS Bios)',
                'console_slug' => 'sega-genesis',
                'files' => 'bios_MD.bin',
                'version' => 'TradeMark Security System (TMSS)',
                'size' => '1 KB',
                'format' => '.BIN',
                'md5' => '8c831bf59a60c2e699b7d9341624624f',
                'sha1' => 'ae65f05322fafbf2014ff065c585df9b066a733f',
                'emulator' => 'Genesis Plus GX, BlastEm, RetroArch',
                'download_url' => 'https://pub-1b8008184ad14b7b9c5a25fe74b145b6.r2.dev/vault/bios/sega-genesis-megadrive-tmss-bios.zip',
                'description' => 'BIOS de comprobación TMSS para Sega Mega Drive / Genesis (muestra "Produced by or under license from Sega Enterprises LTD").',
                'order' => 10,
            ],
            [
                'system' => 'Sega Master System & Game Gear',
                'console_slug' => 'sega-genesis',
                'files' => 'bios_SMS.sms, bios_GG.gg, Missile Defense 3D BIOS',
                'version' => 'USA / Europe / Japan',
                'size' => '399 KB',
                'format' => '.SMS / .BIN',
                'md5' => '59fbc0ce9c985fc9fcee0162dba03da7',
                'sha1' => '00e5a920b31830f664eff321ea0d6c203ff39134',
                'emulator' => 'Genesis Plus GX, MasterGear, RetroArch',
                'download_url' => 'https://pub-1b8008184ad14b7b9c5a25fe74b145b6.r2.dev/vault/bios/sega-master-system-game-gear.zip',
                'description' => 'BIOS con juegos integrados (Alex Kidd, Snail Maze) para Sega Master System y Game Gear.',
                'order' => 11,
            ],
            [
                'system' => 'SEGA 101 BIOS',
                'console_slug' => 'sega-genesis',
                'files' => 'sega_101.bin',
                'version' => 'Official Revision',
                'size' => '1.0 MB',
                'format' => '.BIN',
                'md5' => 'd2d53b863c3ae0ab6573f9c31053a2a5',
                'sha1' => 'e4eb49e5bba093b0ee453e2754653ae83e9980b5',
                'emulator' => 'Mednafen, Kronos',
                'download_url' => 'https://pub-1b8008184ad14b7b9c5a25fe74b145b6.r2.dev/vault/bios/sega-101-bios.zip',
                'description' => 'BIOS de desarrollo y verificación para hardware Sega.',
                'order' => 12,
            ],
            [
                'system' => 'Nintendo DS Bios & Firmware Pack',
                'console_slug' => 'nintendo-ds',
                'files' => 'biosnds7.rom, biosnds9.rom, firmware.bin',
                'version' => 'ARM7 & ARM9 Clean Firmware Dump',
                'size' => '270 KB',
                'format' => '.ROM / .BIN',
                'md5' => 'd1a34e1d87acd6b3fd076faf35f50aa0',
                'sha1' => '5b8f26728d2629b2a340a78d4a80873f3878b8b7',
                'emulator' => 'MelonDS, DeSmuME, DraStic',
                'download_url' => 'https://pub-1b8008184ad14b7b9c5a25fe74b145b6.r2.dev/vault/bios/nintendo-ds-bios-firmware-pack.rar',
                'description' => 'Binarios ARM7 y ARM9 indispensables para arranque del menú nativo, calibración de pantalla y juego inalámbrico en MelonDS.',
                'order' => 13,
            ],
            [
                'system' => 'Game Boy Advance (GBA) Bios',
                'console_slug' => 'game-boy-advance',
                'files' => 'gba_bios.bin, gba (W).gba',
                'version' => 'Official World Release',
                'size' => '20 KB',
                'format' => '.BIN',
                'md5' => 'c4c7c39dd274a05574d073114cca97bf',
                'sha1' => '49e20130707454a879ef3e3a7329f1589734d1eb',
                'emulator' => 'mGBA, VisualBoyAdvance, RetroArch',
                'download_url' => 'https://pub-1b8008184ad14b7b9c5a25fe74b145b6.r2.dev/vault/bios/game-boy-advance-gba-bios.7z',
                'description' => 'BIOS original de Nintendo Game Boy Advance. Permite el sonido de arranque clásico y máxima compatibilidad en mGBA.',
                'order' => 14,
            ],
            [
                'system' => 'Game Boy Bios Pack (GB, GBC, GBA)',
                'console_slug' => 'game-boy',
                'files' => 'gb_bios.bin, gbc_bios.bin, gb_dmg0_rom.bin, gba (J) debug.gba',
                'version' => 'DMG / Game Boy Color / Advance Complete',
                'size' => '20 KB',
                'format' => '.BIN / .GBA',
                'md5' => 'c4c7c39dd274a05574d073114cca97bf',
                'sha1' => '49e20130707454a879ef3e3a7329f1589734d1eb',
                'emulator' => 'mGBA, SameBoy, Gambatte, BGB',
                'download_url' => 'https://pub-1b8008184ad14b7b9c5a25fe74b145b6.r2.dev/vault/bios/game-boy-bios-pack-gb-gbc-gba.7z',
                'description' => 'Pack completo de arranque para toda la familia Game Boy (DMG original, Game Boy Pocket y Game Boy Color con paletas de color).',
                'order' => 15,
            ],
            [
                'system' => 'Nintendo GameCube (GCN) IPL Bios',
                'console_slug' => 'gamecube',
                'files' => 'EUR/IPL.bin, USA/IPL.bin, JAP/IPL.bin',
                'version' => 'Initial Program Loader (USA / EUR / JPN)',
                'size' => '3.3 MB',
                'format' => '.BIN',
                'md5' => '81e2a4223e039f2ce531f0cd69575cd8',
                'sha1' => 'e0e6a20973ff2eec1f66cfbbfaf35a54b7bd6188',
                'emulator' => 'Dolphin Emulator',
                'download_url' => 'https://pub-1b8008184ad14b7b9c5a25fe74b145b6.r2.dev/vault/bios/nintendo-gamecube-gcn-ipl-bios.7z',
                'description' => 'Archivos IPL de Nintendo GameCube para reproducir la intro original del cubo rodante y acceder al menú de tarjetas de memoria en Dolphin.',
                'order' => 16,
            ],
            [
                'system' => 'Nintendo 64DD IPL Bios',
                'console_slug' => 'nintendo-64',
                'files' => 'IPL.z64, 64DD_US.bin, 64DD_JP.bin',
                'version' => 'Japan Retail v1.2 / Development',
                'size' => '3.3 MB',
                'format' => '.Z64 / .BIN',
                'md5' => 'b00564e6f865902d0aded3096d1f019c',
                'sha1' => 'c5c1c8680692d0ff4a3bc10947ea5d58348036be',
                'emulator' => 'Simple64, Ares, Project64',
                'download_url' => 'https://pub-1b8008184ad14b7b9c5a25fe74b145b6.r2.dev/vault/bios/nintendo-64dd-ipl-bios.zip',
                'description' => 'BIOS para la unidad de disco magnético Nintendo 64DD. Requerida para emular títulos como F-Zero X Expansion Kit o Doshin the Giant.',
                'order' => 17,
            ],
            [
                'system' => 'Super Nintendo (SNES) Coprocessor Bios',
                'console_slug' => 'snes',
                'files' => 'dsp1.bin, dsp2.bin, dsp3.bin, dsp4.bin, cx4.bin, st010.bin',
                'version' => 'DSP / SuperFX / Cx4 Coprocessor Dumps',
                'size' => '210 KB',
                'format' => '.BIN',
                'md5' => '6041dae8388e3b49ae797084861d0078',
                'sha1' => '6598d483f6916b04809458aaa6943e74bf670fe6',
                'emulator' => 'Snes9x, bsnes, Mesen, RetroArch',
                'download_url' => 'https://pub-1b8008184ad14b7b9c5a25fe74b145b6.r2.dev/vault/bios/super-nintendo-snes-coprocessor-bios.zip',
                'description' => 'Microcódigo de coprocesadores de soporte SNES para emular Super Mario Kart, Pilotwings, Megaman X2 y Star Fox con precisión.',
                'order' => 18,
            ],
            [
                'system' => 'Famicom Disk System (FDS) Bios',
                'console_slug' => 'nes',
                'files' => 'disksys.rom',
                'version' => 'Official Nintendo Family Computer Disk System',
                'size' => '6 KB',
                'format' => '.ROM',
                'md5' => '6d016da4911345c960fba6edbacc9940',
                'sha1' => '6317e48730e34033f77591350ceb3afaa725a39c',
                'emulator' => 'Mesen, FCEUX, Nestopia, RetroArch',
                'download_url' => 'https://pub-1b8008184ad14b7b9c5a25fe74b145b6.r2.dev/vault/bios/famicom-disk-system-fds-bios.zip',
                'description' => 'BIOS de Famicom Disk System obligatoria para arrancar discos de FDS con la animación de Mario y Luigi corriendo.',
                'order' => 19,
            ],
            [
                'system' => 'Satellaview (BS-X) Bios',
                'console_slug' => 'snes',
                'files' => 'BS-X.bin (English)[NO DRM]',
                'version' => 'English No-DRM Translation Dump',
                'size' => '1.7 MB',
                'format' => '.BIN',
                'md5' => '35a819a3640c1cf240700951fd81c9ba',
                'sha1' => '88d277024d42fae38b249009cb82bd5996cc0bd9',
                'emulator' => 'Snes9x, bsnes, RetroArch',
                'download_url' => 'https://pub-1b8008184ad14b7b9c5a25fe74b145b6.r2.dev/vault/bios/satellaview-bs-x-bios.zip',
                'description' => 'BIOS del módem por satélite BS-X Satellaview de SNES traducida al inglés para emular la ciudad interactiva y emisiones de radio.',
                'order' => 20,
            ],
            [
                'system' => 'NES-SNES Adapter Bios',
                'console_slug' => 'snes',
                'files' => 'nes_to_snes_adapter.bin',
                'version' => 'Adaptor Hardware Dump',
                'size' => '210 KB',
                'format' => '.BIN',
                'md5' => '6041dae8388e3b49ae797084861d0078',
                'sha1' => '6598d483f6916b04809458aaa6943e74bf670fe6',
                'emulator' => 'bsnes, Mesen',
                'download_url' => 'https://pub-1b8008184ad14b7b9c5a25fe74b145b6.r2.dev/vault/bios/nes-snes-adapter-bios.zip',
                'description' => 'BIOS de adaptadores de cartuchos NES sobre consola Super Nintendo.',
                'order' => 21,
            ],
            [
                'system' => 'Microsoft Xbox Bios & MCPX Files',
                'console_slug' => 'xbox-clasica',
                'files' => 'Complex_4627.bin, xbox-5101.bin, mcpx_1.0.bin, mcpx_1.1.bin',
                'version' => 'Retail & Debug MCPX Complete Pack',
                'size' => '1,002 KB',
                'format' => '.BIN',
                'md5' => 'e5e6cb172fb520aae886d42ddbab2cc3',
                'sha1' => 'adfacdfba5ba3d0e00649c05a520ee017816f04e',
                'emulator' => 'xemu, Cxbx-Reloaded',
                'download_url' => 'https://pub-1b8008184ad14b7b9c5a25fe74b145b6.r2.dev/vault/bios/microsoft-xbox-bios-mcpx-files.zip',
                'description' => 'Archivos de arranque MCPX y ROMs de BIOS de Xbox Clásica esenciales para arrancar el dashboard y juegos en xemu.',
                'order' => 22,
            ],
            [
                'system' => 'Microsoft Xbox Extra Bios Set',
                'console_slug' => 'xbox-clasica',
                'files' => 'retail_bios_all.bin, debug_bios.bin',
                'version' => 'v3944 - v5838 Full Pack',
                'size' => '1,002 KB',
                'format' => '.ZIP',
                'md5' => 'e5e6cb172fb520aae886d42ddbab2cc3',
                'sha1' => 'adfacdfba5ba3d0e00649c05a520ee017816f04e',
                'emulator' => 'xemu, Cxbx-Reloaded',
                'download_url' => 'https://pub-1b8008184ad14b7b9c5a25fe74b145b6.r2.dev/vault/bios/microsoft-xbox-extra-bios-set.zip',
                'description' => 'Colección de revisiones de BIOS de Xbox Clásica para emulación de modelos v1.0 a v1.6.',
                'order' => 23,
            ],
            [
                'system' => 'Neo-Geo MVS / AES Complete Bios',
                'console_slug' => NULL,
                'files' => 'neogeo.zip, ng-sfix.rom, ng-sm1.rom, uni-bios_4_0.rom',
                'version' => 'Universe Bios v4.0 + MVS/AES Official Dumps',
                'size' => '58 KB',
                'format' => '.ZIP / .ROM',
                'md5' => '1aea796848f54df32a09def490248680',
                'sha1' => 'c01fdbabec2c505c0e5a18156e0a39dc6ebbb5a9',
                'emulator' => 'FBNeo (FinalBurn Neo), MAME, RetroArch',
                'download_url' => 'https://pub-1b8008184ad14b7b9c5a25fe74b145b6.r2.dev/vault/bios/neo-geo-mvs-aes-complete-bios.zip',
                'description' => 'Pack universal de BIOS de Neo-Geo Arcade MVS y consola AES con Universe Bios para activar trampas, selector de región y jukebox.',
                'order' => 24,
            ],
            [
                'system' => 'Neo-Geo CD Bios Pack',
                'console_slug' => NULL,
                'files' => 'neocd.bin, uni-bioscd-33.rom, top-loading.bin',
                'version' => 'Uni-Bios CD v3.3 + Official SNK CD',
                'size' => '372 KB',
                'format' => '.ROM / .BIN',
                'md5' => 'e2ec14752f65aef00fc33e68cf2fc301',
                'sha1' => '4beb7539d4509ccb1cf97929b1f053847afc309e',
                'emulator' => 'FBNeo, NeoCD, RetroArch',
                'download_url' => 'https://pub-1b8008184ad14b7b9c5a25fe74b145b6.r2.dev/vault/bios/neo-geo-cd-bios-pack.zip',
                'description' => 'BIOS para Neo-Geo CD con reducción de tiempos de carga gracias a Uni-Bios CD.',
                'order' => 25,
            ],
            [
                'system' => 'MAME Complete BIOS Pack (v0.133+)',
                'console_slug' => NULL,
                'files' => 'Atomiswave, Naomi, Hikaru, Chihiro, Triforce, Aleck64, Hyper NeoGeo 64',
                'version' => 'Complete 45 Arcade Systems Pack',
                'size' => '25.6 MB',
                'format' => '.RAR / .ZIP',
                'md5' => '74b4772289511c9309387d32e2081ffa',
                'sha1' => 'd90b8506aa23d71b5f8fc0774e411e74dd93fa59',
                'emulator' => 'MAME, FinalBurn Neo, RetroArch',
                'download_url' => 'https://pub-1b8008184ad14b7b9c5a25fe74b145b6.r2.dev/vault/bios/mame-complete-bios-pack-v0133.rar',
                'description' => 'Conjunto completo de 45 BIOS de placas recreativas arcade: Atomiswave, Naomi 1/2, Chihiro, Triforce, System 573, Polygame Master y más.',
                'order' => 26,
            ],
            [
                'system' => 'MESS (Complete Computer BIOS Pack)',
                'console_slug' => NULL,
                'files' => 'Vintage Microcomputers & Home System Bios',
                'version' => 'Multi Emulator Super System Set',
                'size' => '34.8 MB',
                'format' => '.ZIP',
                'md5' => '973e21b1f2fe25fb911c7b1954d5582b',
                'sha1' => '4b417dd86405a1c9d9d923e176fadfbf2a59de1e',
                'emulator' => 'MAME, RetroArch',
                'download_url' => 'https://pub-1b8008184ad14b7b9c5a25fe74b145b6.r2.dev/vault/bios/mess-complete-computer-bios-pack.zip',
                'description' => 'Colección de BIOS de ordenadores personales clásicos (Commodore, Sinclair ZX, TRS-80, Amstrad CPC).',
                'order' => 27,
            ],
            [
                'system' => 'ST-V (Sega Titan Video) Arcade Bios',
                'console_slug' => 'sega-genesis',
                'files' => 'stv.zip, stvbios.bin',
                'version' => 'USA / Europe / Japan Titan Arcade',
                'size' => '495 KB',
                'format' => '.BIN / .ZIP',
                'md5' => '235641ecb40312d46f183aa9d91cabc9',
                'sha1' => '1e547b14456b27559403275b437590aca977bba8',
                'emulator' => 'MAME, Kronos, RetroArch',
                'download_url' => 'https://pub-1b8008184ad14b7b9c5a25fe74b145b6.r2.dev/vault/bios/st-v-sega-titan-video-arcade-bios.zip',
                'description' => 'BIOS para la placa arcade Sega Titan Video basada en la arquitectura Sega Saturn.',
                'order' => 28,
            ],
            [
                'system' => 'PC Engine & TurboGrafx-CD Bios',
                'console_slug' => NULL,
                'files' => 'syscard1.pce, syscard2.pce, syscard3.pce, games_express.pce',
                'version' => 'System Card v1.0, v2.0, v3.0 (RetroArch Verified)',
                'size' => '279 KB',
                'format' => '.PCE / .BIN',
                'md5' => 'dd8b20371877c8971a719da9dd1261de',
                'sha1' => 'e7bc858ed74f05e09b312558fd7032a83f2b7c3f',
                'emulator' => 'Beetle PCE Fast, Mednafen, RetroArch',
                'download_url' => 'https://pub-1b8008184ad14b7b9c5a25fe74b145b6.r2.dev/vault/bios/pc-engine-turbografx-cd-bios.7z',
                'description' => 'Tarjetas de sistema System Card 1.0, 2.0 y Super System Card 3.0 para cargar discos en PC Engine CD y TurboGrafx-16.',
                'order' => 29,
            ],
            [
                'system' => 'PC-FX Bios (NEC)',
                'console_slug' => NULL,
                'files' => 'pcfx.rom',
                'version' => 'NEC PC-FX Clean Dump',
                'size' => '773 KB',
                'format' => '.ROM',
                'md5' => '62f170c9aeacf25dcf7126987c0a00a4',
                'sha1' => '4da759d842eed156b75d37a4abf2d0faab1a1344',
                'emulator' => 'Beetle PC-FX, Mednafen',
                'download_url' => 'https://pub-1b8008184ad14b7b9c5a25fe74b145b6.r2.dev/vault/bios/pc-fx-bios-nec.zip',
                'description' => 'BIOS de la consola sucesora de 32 bits de NEC, PC-FX. Verificada para Mednafen.',
                'order' => 30,
            ],
            [
                'system' => 'Commodore Amiga BIOS Pack (Kickstart)',
                'console_slug' => NULL,
                'files' => 'Kickstart 1.2, 1.3, 2.0, 3.0, 3.1, 4.0.rom',
                'version' => 'Cloanto Verified Kickstart Collection',
                'size' => '1.7 MB',
                'format' => '.ROM',
                'md5' => 'dd423ce09b08d5176a962b7008a8beef',
                'sha1' => '54568458bc881c6b61b9811fe9b852dbcc4458b2',
                'emulator' => 'WinUAE, FS-UAE, PUAE, RetroArch',
                'download_url' => 'https://pub-1b8008184ad14b7b9c5a25fe74b145b6.r2.dev/vault/bios/commodore-amiga-bios-pack-kickstart.zip',
                'description' => 'ROMs de arranque Kickstart completas para ordenadores Commodore Amiga 500, 600, 1200 y 4000.',
                'order' => 31,
            ],
            [
                'system' => 'Microsoft MSX & MSX2 Bios',
                'console_slug' => NULL,
                'files' => 'MSX.ROM, MSX2.ROM, MSX2EXT.ROM, FMPAC.ROM',
                'version' => 'MSX / MSX2 / MSX2+ Clean ROMs',
                'size' => '229 KB',
                'format' => '.ROM',
                'md5' => 'a8e146454ec91c859dcdcbd63d4ba5f5',
                'sha1' => '9215fcf234968c7f4a43668fb516c976516fb217',
                'emulator' => 'openMSX, fMSX, BlueMSX',
                'download_url' => 'https://pub-1b8008184ad14b7b9c5a25fe74b145b6.r2.dev/vault/bios/microsoft-msx-msx2-bios.7z',
                'description' => 'Colección de extensiones de BIOS para el estándar japonés de ordenadores Microsoft MSX y MSX2.',
                'order' => 32,
            ],
            [
                'system' => 'Panasonic 3DO Interactive Bios',
                'console_slug' => NULL,
                'files' => 'panafz10.bin, goldstar.bin, sanyo.bin',
                'version' => 'FZ-10 & FZ-1 (Perfect for RetroArch)',
                'size' => '554 KB',
                'format' => '.BIN',
                'md5' => '6e0817efdf573acab86577c5187704a7',
                'sha1' => '94499deecc0208a1a5623199573b97d6e20943af',
                'emulator' => 'Opera (4DO), Phoenix, RetroArch',
                'download_url' => 'https://pub-1b8008184ad14b7b9c5a25fe74b145b6.r2.dev/vault/bios/panasonic-3do-interactive-bios.zip',
                'description' => 'BIOS original de la consola 3DO FZ-10 para emular juegos de 32 bits con audio y FMV fluido en el núcleo Opera.',
                'order' => 33,
            ],
            [
                'system' => 'Philips CD-i Bios Pack',
                'console_slug' => NULL,
                'files' => 'cdi200.rom, cdi205.rom, cdi220.rom, cdi490.rom, cdi910.rom',
                'version' => 'Mono-I / Mono-II Full Collection',
                'size' => '1.1 MB',
                'format' => '.ROM',
                'md5' => 'ea70aeea3c22123a93ad986547067793',
                'sha1' => 'c7801e323598f21a47e1fea5978db2cf55abc8dc',
                'emulator' => 'SAME CDi, MAME',
                'download_url' => 'https://pub-1b8008184ad14b7b9c5a25fe74b145b6.r2.dev/vault/bios/philips-cd-i-bios-pack.zip',
                'description' => 'Archivos de arranque de la plataforma multimedia Philips CD-i para arrancar Zelda: Wand of Gamelon y Hotel Mario.',
                'order' => 34,
            ],
            [
                'system' => 'Atari Bios Collection (5200, 7800, Lynx, Jaguar)',
                'console_slug' => NULL,
                'files' => '7800 BIOS.rom, Jaguar BIOS.rom, Jaguar CD BIOS.rom, Lynx Boot.bin',
                'version' => 'Atari 5200 / 7800 / Lynx / Jaguar / TOS',
                'size' => '231 KB',
                'format' => '.ROM / .IMG / .BIN',
                'md5' => '50182ce0abaac1cbfd97af789b2891f1',
                'sha1' => '16ef2b3abed0e0856d1015f1a0f9b9ec40b69076',
                'emulator' => 'BigPEmu, Handy, ProSystem, Stella',
                'download_url' => 'https://pub-1b8008184ad14b7b9c5a25fe74b145b6.r2.dev/vault/bios/atari-bios-collection-5200-7800-lynx-jaguar.7z',
                'description' => 'Colección exhaustiva de BIOS de Atari: 5200, 7800 ProSystem, Atari Lynx portátil y Atari Jaguar 64-bit.',
                'order' => 35,
            ],
            [
                'system' => 'ColecoVision Bios',
                'console_slug' => NULL,
                'files' => 'coleco.rom, ColecoVision (No Intro).rom',
                'version' => 'Clean Official Dump',
                'size' => '17 KB',
                'format' => '.ROM',
                'md5' => '49500b200c04f2d4cdcef7186b2d24ac',
                'sha1' => 'b71eaf569c365f0879129150d2c6375e478a5171',
                'emulator' => 'Gearcoleco, ColEm, RetroArch',
                'download_url' => 'https://pub-1b8008184ad14b7b9c5a25fe74b145b6.r2.dev/vault/bios/colecovision-bios.zip',
                'description' => 'BIOS original de la consola clásica de segunda generación ColecoVision.',
                'order' => 36,
            ],
            [
                'system' => 'Intellivision BIOS Set',
                'console_slug' => NULL,
                'files' => 'exec.bin, grom.bin, ivoice.bin, ecs.bin',
                'version' => 'Mattel Electronics Verified',
                'size' => '21 KB',
                'format' => '.BIN',
                'md5' => 'b86b50d6b7bfe2f76d85c2564611f0a6',
                'sha1' => 'b57de8f54ecb5cca138d7323151e4867dc4b5482',
                'emulator' => 'FreeIntv, jzIntv, RetroArch',
                'download_url' => 'https://pub-1b8008184ad14b7b9c5a25fe74b145b6.r2.dev/vault/bios/intellivision-bios-set.zip',
                'description' => 'Archivos EXEC y GROM requeridos por Mattel Electronics Intellivision para ejecutar títulos de los años 80.',
                'order' => 37,
            ],
            [
                'system' => 'Apple Mac Quadra Bios',
                'console_slug' => NULL,
                'files' => 'Mac_Quadra_650.rom, Quadra_700.rom',
                'version' => 'Motorola 68040 Macintosh ROM',
                'size' => '492 KB',
                'format' => '.ROM',
                'md5' => '0176f99f5fa1314daa48ea4d8f34188f',
                'sha1' => '250e3282a4d746def3ab355d5bbc15666621ff22',
                'emulator' => 'Basilisk II, SheepShaver',
                'download_url' => 'https://pub-1b8008184ad14b7b9c5a25fe74b145b6.r2.dev/vault/bios/apple-mac-quadra-bios.zip',
                'description' => 'ROM de arranque de ordenadores Apple Macintosh Quadra con procesador Motorola 68040 para Basilisk II.',
                'order' => 38,
            ],
            [
                'system' => 'Gamars & XBand Copier Modem Bios',
                'console_slug' => 'snes',
                'files' => 'xband_modem.bin, gamars_copier.bin',
                'version' => 'SNES XBand Modem / Game Boy Gamars Copier',
                'size' => '476 KB',
                'format' => '.BIN',
                'md5' => '499bb6c4557222c38f9ba61ff22a3ad5',
                'sha1' => '5ee6cc500e98855b9538ffb1dcffba87bba30142',
                'emulator' => 'bsnes, Mesen, Snes9x',
                'download_url' => 'https://pub-1b8008184ad14b7b9c5a25fe74b145b6.r2.dev/vault/bios/gamars-xband-copier-modem-bios.zip',
                'description' => 'BIOS para periféricos históricos: módem en línea XBand para Super Nintendo y copiador Gamars de Game Boy.',
                'order' => 39,
            ],
        ];

        foreach ($biosData as $item) {
            $console = !empty($item['console_slug']) ? Console::where('slug', $item['console_slug'])->first() : null;
            $item['console_id'] = $console?->id;
            $item['is_active'] = true;

            Bios::updateOrCreate(
                ['system' => $item['system']],
                $item
            );
        }

        // 2. EMULATORS DIRECTORY (19 Emuladores Oficiales y Modernos)
        $emulatorsData = [
            // PLAYSTATION
            [
                'name' => 'PCSX2',
                'system' => 'PlayStation 2 (PS2)',
                'icon' => 'disc',
                'platforms' => ['Windows', 'Linux', 'macOS'],
                'version' => 'v2.2 Stable',
                'features' => ['Upscaling 4K / 8K', 'Vulkan & DirectX 12', 'RetroAchievements', 'Soporte DualSense & Widescreen'],
                'license' => 'GPLv3 Open Source',
                'website' => 'https://pcsx2.net',
                'download_url' => 'https://pcsx2.net/downloads',
                'description' => 'El emulador definitivo de PlayStation 2. Permite jugar prácticamente el 99% del catálogo con texturas HD, 60 FPS y mejoras gráficas sin precedentes.',
                'order' => 1,
            ],
            [
                'name' => 'NetherSX2 / AetherSX2',
                'system' => 'PlayStation 2 (Android)',
                'icon' => 'smartphone',
                'platforms' => ['Android'],
                'version' => 'v1.5 Community Mod',
                'features' => ['Optimización Snapdragon / Mali', 'Vulkan Renderer', 'Controles Táctiles Personalizables', 'Sin Publicidad'],
                'license' => 'LGPL / Freeware',
                'website' => 'https://github.com/Trixarian/NetherSX2-patch',
                'download_url' => 'https://github.com/Trixarian/NetherSX2-patch/releases',
                'description' => 'La versión más depurada y recomendada para emular PlayStation 2 en smartphones y tablets Android, libre de malware y anuncios.',
                'order' => 2,
            ],
            [
                'name' => 'DuckStation',
                'system' => 'PlayStation 1 (PS1 / PSX)',
                'icon' => 'disc-2',
                'platforms' => ['Windows', 'Android', 'Linux', 'macOS'],
                'version' => 'Latest Rolling Release',
                'features' => ['PGXP (Elimina temblores poligonales)', 'Overclock CPU a 60 FPS', 'Corrección de perspectiva de texturas', 'Upscaling 4K'],
                'license' => 'GPLv3 Open Source',
                'website' => 'https://github.com/stenzek/duckstation',
                'download_url' => 'https://github.com/stenzek/duckstation/releases',
                'description' => 'El mejor emulador de PlayStation 1 existente. Su tecnología PGXP estabiliza los gráficos 3D ofreciendo una remasterización instantánea de cada juego.',
                'order' => 3,
            ],
            [
                'name' => 'RPCS3',
                'system' => 'PlayStation 3 (PS3)',
                'icon' => 'cpu',
                'platforms' => ['Windows', 'Linux', 'macOS'],
                'version' => 'v0.0.35 Alpha',
                'features' => ['Resolución 4K/8K Nativa', 'Desbloqueo hasta 120 FPS', 'Vulkan Renderer Avanzado', 'Soporte PSN Local / Netplay'],
                'license' => 'GPLv2 Open Source',
                'website' => 'https://rpcs3.net',
                'download_url' => 'https://rpcs3.net/download',
                'description' => 'Emulador open-source de PlayStation 3 con más de 2.500 títulos totalmente jugables a altas tasas de cuadros por segundo.',
                'order' => 4,
            ],
            [
                'name' => 'PPSSPP',
                'system' => 'PlayStation Portable (PSP)',
                'icon' => 'smartphone',
                'platforms' => ['Windows', 'Android', 'iOS', 'macOS', 'Linux'],
                'version' => 'v1.18.1',
                'features' => ['Upscaling HD/4K', 'Soporte Mandos Bluetooth', 'Filtros FXAA & CRT', 'Multijugador Ad-hoc Online'],
                'license' => 'GPLv2+ Open Source',
                'website' => 'https://www.ppsspp.org',
                'download_url' => 'https://www.ppsspp.org/download/',
                'description' => 'El estándar absoluto en emulación de PSP. Extremadamente rápido y fluido incluso en dispositivos móviles de gama baja.',
                'order' => 5,
            ],

            // NINTENDO
            [
                'name' => 'Dolphin Emulator',
                'system' => 'Nintendo GameCube & Wii',
                'icon' => 'box',
                'platforms' => ['Windows', 'Android', 'macOS', 'Linux'],
                'version' => 'v2407 / Rolling Dev',
                'features' => ['Netplay Multijugador', 'Packs de Texturas HD', 'Soporte Mandos Reales Wiimote & GameCube', 'Resolución 4K'],
                'license' => 'GPLv2+ Open Source',
                'website' => 'https://dolphin-emu.org',
                'download_url' => 'https://dolphin-emu.org/download/',
                'description' => 'Legendario emulador para GameCube y Wii. Rendimiento impecable en ordenadores y teléfonos con miles de horas de optimización.',
                'order' => 6,
            ],
            [
                'name' => 'Lime3DS / PabloMK7 Citra',
                'system' => 'Nintendo 3DS',
                'icon' => 'layers',
                'platforms' => ['Windows', 'Android', 'macOS', 'Linux'],
                'version' => 'Latest Active Fork',
                'features' => ['Resolución Escalada 4K', 'Soporte Giroscopio y Micrófono', 'Multijugador Local / Salas Online', 'Filtros Estereoscópicos'],
                'license' => 'GPLv2 Open Source',
                'website' => 'https://github.com/PabloMK7/citra',
                'download_url' => 'https://github.com/PabloMK7/citra/releases',
                'description' => 'Los sucesores activos de Citra con mejoras continuas de rendimiento, compatibilidad multijugador y soporte Vulkan para Nintendo 3DS.',
                'order' => 7,
            ],
            [
                'name' => 'MelonDS',
                'system' => 'Nintendo DS / DSi',
                'icon' => 'laptop',
                'platforms' => ['Windows', 'Linux', 'macOS', 'Android'],
                'version' => 'v1.0 RC',
                'features' => ['Renderizado OpenGL 3D', 'Wi-Fi Online Nintendo WFC', 'Micrófono y Pantalla Táctil', 'Modo DSi Completo'],
                'license' => 'GPLv3 Open Source',
                'website' => 'https://melonds.kuribo64.net',
                'download_url' => 'https://melonds.kuribo64.net/downloads.php',
                'description' => 'Emulador de Nintendo DS de alta fidelidad enfocado en precisión de hardware milimétrica y conexión inalámbrica real.',
                'order' => 8,
            ],
            [
                'name' => 'DraStic DS Emulator',
                'system' => 'Nintendo DS (Android)',
                'icon' => 'smartphone',
                'platforms' => ['Android'],
                'version' => 'v2.6 Stable (Gratis)',
                'features' => ['Máxima Velocidad en Móviles', 'Filtros HD 3D', 'Avance Rápido (Fast-Forward)', 'Sincronización en la Nube'],
                'license' => 'Freeware',
                'website' => 'https://play.google.com/store/apps/details?id=com.dsemu.drastic',
                'download_url' => 'https://play.google.com/store/apps/details?id=com.dsemu.drastic',
                'description' => 'El emulador de Nintendo DS más veloz para Android, ahora completamente gratuito para todos los usuarios.',
                'order' => 9,
            ],
            [
                'name' => 'mGBA',
                'system' => 'Game Boy Advance / GBC / GB',
                'icon' => 'gamepad',
                'platforms' => ['Windows', 'macOS', 'Linux', 'Android', 'Steam Deck'],
                'version' => 'v0.10.4',
                'features' => ['Cable Link Local y por Red', 'Sensor Solar y Giroscopio', 'Rebobinado en Tiempo Real', 'Compatibilidad 100% con ROM Hacks'],
                'license' => 'MPL 2.0 Open Source',
                'website' => 'https://mgba.io',
                'download_url' => 'https://mgba.io/downloads.html',
                'description' => 'El emulador de Game Boy Advance más preciso y ligero disponible, ideal para ROM hacks de Pokémon y juegos clásicos.',
                'order' => 10,
            ],
            [
                'name' => 'Simple64',
                'system' => 'Nintendo 64 (N64)',
                'icon' => 'tv',
                'platforms' => ['Windows', 'Linux'],
                'version' => 'v2024.08',
                'features' => ['Plugin ParaLLEl RDP/RSP Vulkan', 'Emulación de Ciclo Exacto', 'Soporte 64DD', 'Sin Configuración Compleja'],
                'license' => 'GPLv3 Open Source',
                'website' => 'https://simple64.github.io',
                'download_url' => 'https://simple64.github.io',
                'description' => 'Emulador de Nintendo 64 moderno basado en precisión que elimina fallos visuales gracias al renderer Vulkan ParaLLEl.',
                'order' => 11,
            ],
            [
                'name' => 'Project64',
                'system' => 'Nintendo 64 (N64)',
                'icon' => 'monitor',
                'platforms' => ['Windows', 'Android'],
                'version' => 'v3.0.1 Stable',
                'features' => ['Plugins de Gráficos y Sonido', 'Soporte Texturas de Alta Resolución', 'Netplay Kaillera', 'Trucos Gameshark'],
                'license' => 'GPLv2 Open Source',
                'website' => 'https://www.pj64-emu.com',
                'download_url' => 'https://www.pj64-emu.com',
                'description' => 'El emulador clásico de Nintendo 64 para Windows con amplio soporte para paquetes de texturas HD de la comunidad.',
                'order' => 12,
            ],
            [
                'name' => 'Snes9x',
                'system' => 'Super Nintendo (SNES)',
                'icon' => 'gamepad-2',
                'platforms' => ['Windows', 'Android', 'macOS', 'Linux'],
                'version' => 'v1.63',
                'features' => ['Filtros CRT y xBRZ', 'Soporte MSU-1 (Audio CD)', 'Rebobinado y Avance Rápido', 'Netplay'],
                'license' => 'Open Source',
                'website' => 'https://github.com/snes9xgit/snes9x',
                'download_url' => 'https://github.com/snes9xgit/snes9x/releases',
                'description' => 'El referente indiscutible para jugar Super Nintendo. Ligero, potente y con soporte completo para bandas sonoras orquestadas MSU-1.',
                'order' => 13,
            ],
            [
                'name' => 'Mesen',
                'system' => 'NES, SNES, Game Boy & PC Engine',
                'icon' => 'grid',
                'platforms' => ['Windows', 'Linux'],
                'version' => 'v2.0.0 Multi-System',
                'features' => ['Precisión de Ciclo Exacto', 'Herramientas de Depuración y HD Packs', 'Soporte FDS y Satellaview', 'Audio Estéreo Enriquecido'],
                'license' => 'GPLv3 Open Source',
                'website' => 'https://www.mesen.ca',
                'download_url' => 'https://github.com/SourMesen/Mesen2/releases',
                'description' => 'Emulador multi-sistema de máxima fidelidad técnica para consolas de 8 y 16 bits de Nintendo y NEC.',
                'order' => 14,
            ],

            // SEGA & XBOX
            [
                'name' => 'Flycast',
                'system' => 'Sega Dreamcast, Naomi & Atomiswave',
                'icon' => 'radio',
                'platforms' => ['Windows', 'Android', 'macOS', 'Linux', 'iOS'],
                'version' => 'v2.3 Stable',
                'features' => ['Renderizado Vulkan', 'Netplay Online Battle', 'Texturas HD Custom', 'Widescreen Hacks'],
                'license' => 'GPLv2 Open Source',
                'website' => 'https://github.com/flyinghead/flycast',
                'download_url' => 'https://github.com/flyinghead/flycast/releases',
                'description' => 'El emulador más completo y avanzado para Sega Dreamcast y placas recreativas arcade Naomi y Atomiswave.',
                'order' => 15,
            ],
            [
                'name' => 'Redream',
                'system' => 'Sega Dreamcast',
                'icon' => 'play',
                'platforms' => ['Windows', 'Android', 'macOS', 'Linux', 'Raspberry Pi'],
                'version' => 'v1.5.0',
                'features' => ['Arranque Plug & Play Sin BIOS', 'Resolución 4K (Lite/Premium)', 'Interfaz Visual Moderna', 'Mapeo Automático de Mandos'],
                'license' => 'Freemium',
                'website' => 'https://redream.io',
                'download_url' => 'https://redream.io/download',
                'description' => 'La experiencia de emulación de Dreamcast más amigable y visualmente limpia. Conectar el mando y jugar al instante.',
                'order' => 16,
            ],
            [
                'name' => 'xemu',
                'system' => 'Xbox Clásica (Original)',
                'icon' => 'terminal',
                'platforms' => ['Windows', 'macOS', 'Linux'],
                'version' => 'v0.8.29',
                'features' => ['Resolución Escalada', 'Netplay por System Link', 'Soporte Mandos XInput', 'Emulación de Disco Duro'],
                'license' => 'GPLv2 Open Source',
                'website' => 'https://xemu.app',
                'download_url' => 'https://xemu.app',
                'description' => 'Emulador de código abierto para la primera consola Xbox original. Compatible con Halo, Forza y cientos de clásicos.',
                'order' => 17,
            ],
            [
                'name' => 'Mednafen',
                'system' => 'Sega Saturn, PS1 & PC Engine',
                'icon' => 'code',
                'platforms' => ['Windows', 'Linux'],
                'version' => 'v1.32.1',
                'features' => ['Emulación Más Precisa de Sega Saturn', 'Renderizado sin artefactos', 'Entrada de Baja Latencia'],
                'license' => 'GPLv2 Open Source',
                'website' => 'https://mednafen.github.io',
                'download_url' => 'https://mednafen.github.io/releases/',
                'description' => 'Motor de emulación multi-sistema venerado por su precisión inflexible de hardware, especialmente en Sega Saturn.',
                'order' => 18,
            ],

            // TODO EN UNO
            [
                'name' => 'RetroArch',
                'system' => 'Multi-Sistema Universal (Todo en Uno)',
                'icon' => 'layers',
                'platforms' => ['Windows', 'Android', 'iOS', 'macOS', 'Linux', 'Steam Deck', 'Xbox'],
                'version' => 'v1.19.1',
                'features' => ['Más de 80 Núcleos Libretro', 'Shaders CRT Retro y Slang', 'RetroAchievements', 'Netplay Cross-platform'],
                'license' => 'GPLv3 Open Source',
                'website' => 'https://www.retroarch.com',
                'download_url' => 'https://www.retroarch.com/?page=platforms',
                'description' => 'La suite universal de emulación frontend. Permite unificar toda tu colección de videojuegos retro bajo una interfaz única tipo consola.',
                'order' => 19,
            ],
        ];

        foreach ($emulatorsData as $item) {
            $item['is_active'] = true;
            Emulator::updateOrCreate(
                ['name' => $item['name']],
                $item
            );
        }
    }
}
