<?php

namespace Database\Seeders;

use App\Models\Console;
use Illuminate\Database\Seeder;

class ConsoleSeeder extends Seeder
{
    public function run(): void
    {
        $consoles = [
            // Sony PlayStation Family
            [
                'name' => 'PlayStation',
                'slug' => 'playstation',
                'short_name' => 'PS1',
                'manufacturer' => 'Sony',
                'generation' => 5,
                'release_year' => 1994,
                'description' => 'La consola de 32 bits que revolucionó la industria introduciendo los CDs y gráficos 3D.',
                'recommended_emulator' => 'DuckStation / Beetle PSX',
                'order' => 1,
                'is_featured' => true,
            ],
            [
                'name' => 'PlayStation 2',
                'slug' => 'playstation-2',
                'short_name' => 'PS2',
                'manufacturer' => 'Sony',
                'generation' => 6,
                'release_year' => 2000,
                'description' => 'La consola más vendida de todos los tiempos con una librería legendaria de más de 2,000 títulos.',
                'recommended_emulator' => 'PCSX2 v2.0+ / AetherSX2',
                'order' => 2,
                'is_featured' => true,
            ],
            [
                'name' => 'PlayStation 3',
                'slug' => 'playstation-3',
                'short_name' => 'PS3',
                'manufacturer' => 'Sony',
                'generation' => 7,
                'release_year' => 2006,
                'description' => 'Alta definición con arquitectura Cell Processor y soporte nativo para Blu-Ray.',
                'recommended_emulator' => 'RPCS3',
                'order' => 3,
                'is_featured' => true,
            ],
            [
                'name' => 'PlayStation Portable',
                'slug' => 'psp',
                'short_name' => 'PSP',
                'manufacturer' => 'Sony',
                'generation' => 7,
                'release_year' => 2004,
                'description' => 'Potencia de sobremesa en formato portátil con pantalla panorámica y discos UMD.',
                'recommended_emulator' => 'PPSSPP',
                'order' => 4,
                'is_featured' => true,
            ],
            [
                'name' => 'PlayStation Vita',
                'slug' => 'psvita',
                'short_name' => 'PSV',
                'manufacturer' => 'Sony',
                'generation' => 8,
                'release_year' => 2011,
                'description' => 'Pantalla táctil OLED, doble stick analógico y una biblioteca de culto de JRPGs.',
                'recommended_emulator' => 'Vita3K',
                'order' => 5,
                'is_featured' => true,
            ],

            // Nintendo Family
            [
                'name' => 'Nintendo Entertainment System',
                'slug' => 'nes',
                'short_name' => 'NES',
                'manufacturer' => 'Nintendo',
                'generation' => 3,
                'release_year' => 1983,
                'description' => 'El renacer del videojuego que definió la era dorada de los 8 bits.',
                'recommended_emulator' => 'Mesen / FCEUX',
                'order' => 6,
                'is_featured' => false,
            ],
            [
                'name' => 'Super Nintendo (SNES)',
                'slug' => 'snes',
                'short_name' => 'SNES',
                'manufacturer' => 'Nintendo',
                'generation' => 4,
                'release_year' => 1990,
                'description' => 'La cúspide del pixel art de 16 bits y bandas sonoras orquestadas con chip SPC700.',
                'recommended_emulator' => 'bsnes / Snes9x',
                'order' => 7,
                'is_featured' => true,
            ],
            [
                'name' => 'Nintendo 64',
                'slug' => 'nintendo-64',
                'short_name' => 'N64',
                'manufacturer' => 'Nintendo',
                'generation' => 5,
                'release_year' => 1996,
                'description' => 'Pionera en entornos 3D libres, stick analógico y multijugador a 4 mandos.',
                'recommended_emulator' => 'Simple64 / Ares',
                'order' => 8,
                'is_featured' => true,
            ],
            [
                'name' => 'Nintendo GameCube',
                'slug' => 'gamecube',
                'short_name' => 'GCN',
                'manufacturer' => 'Nintendo',
                'generation' => 6,
                'release_year' => 2001,
                'description' => 'El cubo morado con joyas inolvidables de Nintendo y compatibilidad nativa en alta resolución.',
                'recommended_emulator' => 'Dolphin 5.0+',
                'order' => 9,
                'is_featured' => true,
            ],
            [
                'name' => 'Nintendo Wii',
                'slug' => 'wii',
                'short_name' => 'WII',
                'manufacturer' => 'Nintendo',
                'generation' => 7,
                'release_year' => 2006,
                'description' => 'Revolución del control por movimiento con el Wiimote que conquistó el mundo.',
                'recommended_emulator' => 'Dolphin 5.0+',
                'order' => 10,
                'is_featured' => false,
            ],
            [
                'name' => 'Nintendo Wii U',
                'slug' => 'wii-u',
                'short_name' => 'WIIU',
                'manufacturer' => 'Nintendo',
                'generation' => 8,
                'release_year' => 2012,
                'description' => 'Gamepad con pantalla táctil integrada y primera consola HD de Nintendo.',
                'recommended_emulator' => 'Cemu',
                'order' => 11,
                'is_featured' => false,
            ],
            [
                'name' => 'Nintendo Switch',
                'slug' => 'nintendo-switch',
                'short_name' => 'Switch',
                'manufacturer' => 'Nintendo',
                'generation' => 9,
                'release_year' => 2017,
                'description' => 'Híbrida sobremesa/portátil con el catálogo contemporáneo más aclamado.',
                'recommended_emulator' => 'Ryujinx',
                'order' => 12,
                'is_featured' => true,
            ],
            [
                'name' => 'Game Boy / Game Boy Color',
                'slug' => 'game-boy',
                'short_name' => 'GB',
                'manufacturer' => 'Nintendo',
                'generation' => 4,
                'release_year' => 1989,
                'description' => 'La portátil que creó el fenómeno mundial de Pokémon y Tetris.',
                'recommended_emulator' => 'mGBA / SameBoy',
                'order' => 13,
                'is_featured' => false,
            ],
            [
                'name' => 'Game Boy Advance',
                'slug' => 'game-boy-advance',
                'short_name' => 'GBA',
                'manufacturer' => 'Nintendo',
                'generation' => 6,
                'release_year' => 2001,
                'description' => 'Potencia de 32 bits de bolsillo con una biblioteca de clásicos 2D inagotable.',
                'recommended_emulator' => 'mGBA',
                'order' => 14,
                'is_featured' => true,
            ],
            [
                'name' => 'Nintendo DS',
                'slug' => 'nintendo-ds',
                'short_name' => 'NDS',
                'manufacturer' => 'Nintendo',
                'generation' => 7,
                'release_year' => 2004,
                'description' => 'Doble pantalla con panel táctil inferior y micrófono.',
                'recommended_emulator' => 'MelonDS / DeSmuME',
                'order' => 15,
                'is_featured' => false,
            ],
            [
                'name' => 'Nintendo 3DS',
                'slug' => 'nintendo-3ds',
                'short_name' => '3DS',
                'manufacturer' => 'Nintendo',
                'generation' => 8,
                'release_year' => 2011,
                'description' => 'Efecto estereoscópico 3D sin gafas y una de las mayores bibliotecas de RPGs.',
                'recommended_emulator' => 'Citra / Lime3DS',
                'order' => 16,
                'is_featured' => true,
            ],

            // Sega Family
            [
                'name' => 'Sega Genesis / Mega Drive',
                'slug' => 'sega-genesis',
                'short_name' => 'GEN',
                'manufacturer' => 'Sega',
                'generation' => 4,
                'release_year' => 1988,
                'description' => 'Blast processing, velocidad pura con Sonic y espíritu arcade de 16 bits.',
                'recommended_emulator' => 'Genesis Plus GX',
                'order' => 17,
                'is_featured' => true,
            ],
            [
                'name' => 'Sega Dreamcast',
                'slug' => 'dreamcast',
                'short_name' => 'DC',
                'manufacturer' => 'Sega',
                'generation' => 6,
                'release_year' => 1998,
                'description' => 'Consola de 128 bits adelantada a su época con módem de internet y tarjeta VMU.',
                'recommended_emulator' => 'Flycast',
                'order' => 18,
                'is_featured' => true,
            ],

            // Microsoft Family
            [
                'name' => 'Xbox Clásica',
                'slug' => 'xbox-clasica',
                'short_name' => 'XBOX',
                'manufacturer' => 'Microsoft',
                'generation' => 6,
                'release_year' => 2001,
                'description' => 'La primera consola de Microsoft con arquitectura x86, disco duro interno y Halo.',
                'recommended_emulator' => 'xemu',
                'order' => 19,
                'is_featured' => true,
            ],
            [
                'name' => 'Xbox 360',
                'slug' => 'xbox-360',
                'short_name' => 'X360',
                'manufacturer' => 'Microsoft',
                'generation' => 7,
                'release_year' => 2005,
                'description' => 'La era dorada de Xbox Live, logros, gráficos HD y grandes experiencias multijugador.',
                'recommended_emulator' => 'Xenia Canary',
                'order' => 20,
                'is_featured' => true,
            ],
        ];

        foreach ($consoles as $console) {
            Console::updateOrCreate(['slug' => $console['slug']], $console);
        }
    }
}
